HOST = "irc.twitch.tv"              # This is Twitchs IRC server
PORT = 6667                         # Twitchs IRC server listens on port 6767
NICK = "sprout_bot"            # Twitch username your using for your bot
PASS = "oauth:za9r078fwx8zwd7zc7q9mfeisl0srx" # your Twitch OAuth token
CHAN = "#flaganti"                   # the channel you want the bot to join.
RATE = (20/30) # 20 messages in 30 seconds
MODRATE = (100/30) # 100 messages in 30 seconds
POINTAMOUNT = 100 #How many points you get
TIMERFORPOINTS = 20 #How often you get the points in seconds
BAN_PAT=[]